# Generated by Django 5.2.17 on 2026-09-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="familymember",
            name="tracking_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
