# Generated by Django 5.2.17 on 2026-09-02 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_familymember_tracking_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="familymember",
            name="device_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="family_member_device",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
