# Generated by Django 5.2.17 on 2026-09-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_fcm_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("danger", "Danger"),
                    ("warning", "Warning"),
                    ("info", "Information"),
                    ("assistance", "Assistance"),
                ],
                max_length=20,
            ),
        ),
    ]
