# Generated by Django 5.2.17 on 2026-09-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_alert_alert_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("parent", "Parent"), ("family_member", "Family Member")],
                default="parent",
                max_length=20,
            ),
        ),
    ]
